### ISSUE TITLE
IG embed fails on private post URL (public posts which were made private later on)

### ISSUE THREAD

**Issue by teeaarbee** [MichaelDeBoey/gatsby-remark-embedder#152] opened 2020-11-01 12:41 UTC
- `gatsby-remark-embedder` version: ^4.0.0
- `node` version: v10.16.2
- `npm` (or `yarn`) version: 7.0.2

Relevant code or config

```javascript

```

**What you did:** Added Access token and everything works fine - IG embed posts loads good however, it failed over one scenario - private post link (it was public earlier but now its private )

**What happened:**
So I had one URL which was public post at the time of embedding it into my blog post and later on the post was private so I had to remove the post URL.

This is the response from the server while trying to get the embed post:

![image](https://user-images.githubusercontent.com/65780147/97802823-1b992880-1c6c-11eb-9642-5d5f65e32210.png)

Reproduction repository: 

**Problem description:** Plugin fails to render IG embed posts if it comes across any Private post link or age restricted posts.

**Suggested solution:**  May be we can get to just display a silent message saying 'Post unavailable' or just skip it and move on.

**Comment by MichaelDeBoey** [comment] 2020-11-01 16:31
Hi @teeaarbee! 👋

I remember @pieh implementing a cleaner failing mechanism.
In #75 he added a retry mechanism so we try to fetch it again if it fails.
In #104 he added a cleaner error message whenever it keeps failing.

This is expected behavior, since you would otherwise show the link to the post, which wouldn't be available anyways.

Closing this for now.
Feel free to respond though

**Closed by MichaelDeBoey** 2020-11-01 16:31 UTC
